### ISSUE TITLE
建议新增几种常用路径格式

### ISSUE THREAD

**Issue by ihotte** [imba97/picgo-plugin-ftp-uploader#10]
| 名称          | 介绍                   | 输出示例                                                     |
| ------------- | ---------------------- | ------------------------------------------------------------ |
| {day}         | 当前日期               | 31                                                           |
| {md5sum}      | 图片 MD5 32 位         | 68559cae1081d6836e09b043aa0b3af1                             |
| {sha1sum}     | 图片 SHA1 40 位        | e0c9035898dd52fc65c41454cec9c4d2611bfb37                     |
| {sha256sum}   | 图片 SHA256 64 位      | 9ca030bdec6e900a7ac41fef448a0872a3530443c776383cf69e55916f3ad35f |
| {md5sum:0:6}  | 偏移 0，长度 6         | 68559c                                                       |
| {md5sum:6:-3} | 偏移 6，结束倒数第三位 | ae1081d6836e09b043aa0b3                                      |

支持 md5sum、sha1sum、sha256sum，同时支持 {sum:offset:length} 子串格式。

以便于支持 `{md5sum:0:2}/{md5sum:2:2}/{md5sum}{ext}` 这种散列目录格式，防止单一目录出现太多文件。

**Comment by imba97** [comment]
已在 [picgo-plugin-sftp-uploader#4](https://github.com/imba97/picgo-plugin-sftp-uploader/issues/4#issuecomment-999485930) 回复，这里先关了
