### ISSUE TITLE
ftp上传提示  Cannot read properties of undefined (reading 'host')

### ISSUE THREAD

**Issue by pdsxi415** [imba97/picgo-plugin-ftp-uploader#12]
已解决 是两个配置的网站标识写的不一致所致

**Comment by pdsxi415** [comment]
按照网上的大佬教程修改的
![QQ截图20220109155731](https://user-images.githubusercontent.com/62227567/148674176-10f3c6a3-9d6d-4a75-9823-ce47f3bf9cba.jpg)
配置文件路径换成http也报错

**Comment by imba97** [comment]
👌

**Comment by Ahellowyy** [comment]
牛
