### ISSUE TITLE
通过url地址上传图片会失败

### ISSUE THREAD

**Issue by kkkdkk** [imba97/picgo-plugin-ftp-uploader#13]
已成功设置配置文件，剪切板上传正常，选择文件上传正常，但是通过url上传的文件就永远失败。

2022-01-10 11:10:15 [PicGo ERROR] FTP 发生错误，请检查配置是否正确

**Comment by imba97** [comment]
确实是有这个问题

**Comment by imba97** [comment]
我太懒了，已经被别人修复了 #26
