### ISSUE TITLE
腾讯轻量云服务器使用不了

### ISSUE THREAD

**Issue by hadestoday** [imba97/picgo-plugin-ftp-uploader#14]
你好，我使用腾讯云轻量服务器，不能上传图片，提示我【[PicGo ERROR] FTP 发生错误，请检查配置是否正确 】但是对应的路径会帮我生成相应的文件夹。相同的设置，我使用其他的vps都能正常的使用，请问是什么问题呢？

**Comment by imba97** [comment]
应该就是配置的问题，配置文件你是咋写的
