### ISSUE TITLE
TypeError: Cannot read property 'host' of undefined

### ISSUE THREAD

**Issue by junlin49** [imba97/picgo-plugin-ftp-uploader#15]
大神，配置过程中出现这个问题，搞不懂，求教；
![image](https://user-images.githubusercontent.com/54955030/156315386-0d358c04-f9ef-4f52-b498-77f6a44a83f5.png)
![image](https://user-images.githubusercontent.com/54955030/156315780-47566345-99a5-4681-875e-7d178f32827c.png)
![image](https://user-images.githubusercontent.com/54955030/156315995-8c298696-7afd-4609-a73c-09ae562e1e8f.png)

**Comment by imba97** [comment]
`site`那个地方写`servyou`试试
