### ISSUE TITLE
 TypeError [ERR_INVALID_ARG_TYPE]

### ISSUE THREAD

**Issue by zb4608656** [imba97/picgo-plugin-ftp-uploader#4]
大神，总是报 TypeError [ERR_INVALID_ARG_TYPE]错误，不知道是哪里的问题
![2](https://user-images.githubusercontent.com/44523182/131804530-57ea2157-6a61-480b-9f28-b1080ae5f505.png)

**Comment by imba97** [comment]
看一下配置文件的路径，应该是没获取到配置文件

**Comment by zb4608656** [comment]
确实是配置文件的问题，谢谢

**Comment by imba97** [comment]
麻烦发一下你配置文件的路径 和你填写的配置中的路径

**Comment by zb4608656** [comment]
恩恩，我之前是把配置文件放C:/ftpUploader.json，可能是需要管理员权限，插件读取不到，后来给改到E:/ftpUploader.json，然后就正常了

**Comment by imba97** [comment]
ok
